[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "graphtfactor"
version = "0.1.2"
description = "GraphTFactor: Modeling Protein Sequences as Graphs for Accurate Transcription Factor Prediction"
readme = "README.md"
requires-python = ">=3.10"
license = { file = "LICENSE" }
dependencies = [
    "fair-esm==2.0.0",
    "numba>=0.67.0,<0.69",
    "numpy>=2.5.2,<3",
    "torch>=2.8.0,<3",
    "torch-geometric>=2.8.0.post1,<3",
    "tqdm>=4.67.1,<5",
]

[project.urls]
Homepage = "https://github.com/salvatorecalderaro/GraphTFactor"
Repository = "https://github.com/salvatorecalderaro/GraphTFactor"
Issues = "https://github.com/salvatorecalderaro/GraphTFactor/issues"

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.package-data]
graphtfactor = [
    "checkpoints/**/*.pth"
]
